In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from project_functions import file_range_access

In [9]:
# Opening the files
df = pd.read_csv("../CoilData.csv")
coil_list = df.coil

for coil in coil_list:
    
    B4 = pd.read_csv(f"../Cleaned_data/{coil}B4.csv")
    B5 = pd.read_csv(f"../Cleaned_data/{coil}B5.csv")
    
    print(coil)
    
    # Splitting the Values columns, *change in script?*

    B4.rename(columns = {'Values':'B4_Values'}, inplace = True)
    B5.rename(columns = {'Values':'B5_Values'}, inplace = True)

    # Setting the desired Lengthpoints

    B4 = B4[B4.Lengthpoints >= 140]
    B5 = B5[B5.Lengthpoints >= 140]

    B4 = B4[B4.Lengthpoints <= 170]
    B5 = B5[B5.Lengthpoints <= 170]

    # Finding closest values from B5 Lengthpoints to B4 Lengthpoints.
    # This will then change the Lengthpoint of B5 to the closest matching B4 Lengthpoint.

    index = 0
    B4_array = B4['Lengthpoints'].to_numpy()
    B5_array = B5['Lengthpoints'].to_numpy()

    for lengthpoint in B5.Lengthpoints:
    
        closest = np.abs(B4_array-lengthpoint).argmin()
        closest_element = B4_array[closest]
    
        B5_array[index] = closest_element
        index+=1

    B5.Lengthpoints = B5_array 

    # Creating a merged dataframe of B4 and B5.
    # Adding a difference column to show all width differences in mm.
    # Filling the NaN values with the next value or if not available the previous value.

    # If you don't want any NaN values in the dataframe, you can remove the 'how= 'left'' 
    # from merged_df = pd.merge(B4,B5, how= 'left'). This will then automatically exclude the NaN values.

    merged_df = pd.merge(B4,B5, how= 'left')
    merged_df['difference'] = merged_df['B5_Values']-merged_df['B4_Values']
    merged_df.fillna(method ='bfill', inplace = True)
    merged_df.fillna(method ='pad', inplace = True)

    # We create the values to put into the columns of CoilData

    possible_constriction_count = (merged_df['difference']<=-4).sum()

    diff = merged_df['difference'].min()
    
    constrictions = []
    for each in merged_df['difference']:
        if each <= -0.1:
            constrictions.append(each)

    # We write the information to out CoilData file so we have an overview of which one constricted, what the largest constriction
    # is per coil and how many constrictions of equal to or over 4mm there are.

    coil_index = df.index[df['coil']== coil].tolist()
    
    if len(constrictions) == len(merged_df.difference):  
        df.at[coil_index[0],'Constriction'] = "False"
    elif possible_constriction_count == 1:
        df.at[coil_index[0],'Constriction'] = "False"
    elif -50<= diff <= -4:
        df.at[coil_index[0],'Constriction'] = "True"
        df.at[coil_index[0],'Max separation'] = abs(diff)
        df.at[coil_index[0],'Number of separation points'] = possible_constriction_count
    else:
        df.at[coil_index[0],'Constriction'] = "False"    
    
df.to_csv("../CoilData.csv", index=False)

In [10]:
print(len(constrictions))
print(len(merged_df.difference))

25
63

In [11]:
merged_df

    Lengthpoints  B4_Values  B5_Values  difference
0       140.0513     1224.4     1223.3        -1.1
1       140.5291     1224.3     1222.9        -1.4
2       141.0076     1224.5     1222.9        -1.6
3       141.4861     1224.6     1222.9        -1.7
4       141.9654     1224.7     1222.9        -1.8
..           ...        ...        ...         ...
58      168.0474     1223.2     1225.9         2.7
59      168.5342     1223.4     1226.0         2.6
60      169.0213     1223.4     1226.1         2.7
61      169.5084     1223.7     1226.1         2.4
62      169.9963     1223.8     1226.1         2.4

[63 rows x 4 columns]